site_name: Plane to M-Plane
site_url: https://www.ptomp.org/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/prudhvi9910
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CDOT_India
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/company/cdotindia
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cdot_india/

copyright: |
  &copy; 2023 <a href="https://github.com/prudhvi9910"  target="_blank" rel="noopener">Venkata Prudhvi Dadi</a>